app/urls.py
from django.urls import path

from .models import Item
from .views import ItemFilterView, ItemDetailView, ItemCreateView, ItemUpdateView, ItemDeleteView

# アプリケーションのルーティング設定

urlpatterns = [
    path('detail/<int:pk>/', ItemDetailView.as_view(), name='detail'),
    path('create/', ItemCreateView.as_view(), name='create'),
    path('update/<int:pk>/', ItemUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', ItemDeleteView.as_view(), name='delete'),
    path('', ItemFilterView.as_view(), name='index'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

# ルーティング設定
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

# 管理サイトの見出しを変更可能
#  タイトル；タイトルタグで使用
admin.site.site_title = 'タイトル'
#  サイト名：ログイン画面と管理画面上部の表示
admin.site.site_header = 'サンプルアプリ'
#  メニュー：管理画面の見出し表示
admin.site.index_title = 'メニュー'

app/models.py
from django.db import models

from users.models import User


class Item(models.Model):
    """
    データ定義クラス
      各フィールドを定義する
    参考：
    ・公式 モデルフィールドリファレンス
    https://docs.djangoproject.com/ja/2.1/ref/models/fields/
    """

    # サンプル項目1 文字列
    # sample_1 = models.CharField(
    #     verbose_name='サンプル項目1 文字列',
    #     max_length=20,
    #     blank=True,
    #     null=True,
    # )

    # サンプル項目2 メモ
    sample_2 = models.TextField(
        verbose_name='サンプル項目2 メモ',
        blank=True,
        null=True,
    )

    # サンプル項目3 整数
    sample_3 = models.IntegerField(
        verbose_name='サンプル項目3 整数',
        blank=True,
        null=True,
    )

    # サンプル項目4 浮動小数点
    sample_4 = models.FloatField(
        verbose_name='サンプル項目4 浮動小数点',
        blank=True,
        null=True,
    )

    # サンプル項目5 固定小数点
    sample_5 = models.DecimalField(
        verbose_name='サンプル項目5 固定小数点',
        max_digits=5,
        decimal_places=2,
        blank=True,
        null=True,
    )

    # サンプル項目6 ブール値
    sample_6 = models.BooleanField(
        verbose_name='サンプル項目6 ブール値',
    )

    # サンプル項目7 日付
    sample_7 = models.DateField(
        verbose_name='サンプル項目7 日付',
        blank=True,
        null=True,
    )

    # サンプル項目8 日時
    sample_8 = models.DateTimeField(
        verbose_name='サンプル項目8 日時',
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（固定）
    sample_9_choice = (
        (1, '選択１'),
        (2, '選択２'),
        (3, '選択３'),
    )

    sample_9 = models.IntegerField(
        verbose_name='サンプル項目9_選択肢（固定）',
        choices=sample_9_choice,
        blank=True,
        null=True,
    )

    # サンプル項目9 選択肢（マスタ連動）
    sample_10 = models.ForeignKey(
        User,
        verbose_name='サンプル項目10_選択肢（マスタ連動）',
        blank=True,
        null=True,
        related_name='sample_10',
        on_delete=models.SET_NULL,
    )

    # 以下、管理項目

    # 作成者(ユーザー)
    created_by = models.ForeignKey(
        User,
        verbose_name='作成者',
        blank=True,
        null=True,
        related_name='CreatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 作成時間
    created_at = models.DateTimeField(
        verbose_name='作成時間',
        blank=True,
        null=True,
        editable=False,
    )

    # 更新者(ユーザー)
    updated_by = models.ForeignKey(
        User,
        verbose_name='更新者',
        blank=True,
        null=True,
        related_name='UpdatedBy',
        on_delete=models.SET_NULL,
        editable=False,
    )

    # 更新時間
    updated_at = models.DateTimeField(
        verbose_name='更新時間',
        blank=True,
        null=True,
        editable=False,
    )

    def __str__(self):
        """
        リストボックスや管理画面での表示
        """
        return self.sample_1

    class Meta:
        """
        管理画面でのタイトル表示
        """
        verbose_name = 'サンプル'
        verbose_name_plural = 'サンプル'

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    カスタムユーザー データ定義クラス

    ユーザーの管理項目を増やしたい場合はここにフィールドを定義します。
    例：住所、電話番号など
    """

    # first_name、last_nameの代わりにfull_nameを用意する
    full_name = models.CharField(
        verbose_name='氏名',
        max_length=100,
        blank=True
    )

    # スタッフ権限のデフォルトをTrueに変更する
    # ※ 原則ログインして利用することを想定している。

    is_staff = models.BooleanField(
        _('staff status'),
        default=True,
    )

    # get_full_name()の変更
    def get_full_name(self):
        if self.full_name:
            return self.full_name
        else:
            return self.username + '（氏名未登録）'

    # 選択リストでの表示
    def __str__(self):
        return self.get_full_name()

app/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):
    """
    モデルフォーム構成クラス
    ・公式 モデルからフォームを作成する
    https://docs.djangoproject.com/ja/2.1/topics/forms/modelforms/
    """

    class Meta:
        model = Item
        fields = '__all__'

        # 以下のフィールド以外が入力フォームに表示される
        # AutoField
        # auto_now=True
        # auto_now_add=Ture
        # editable=False

app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django_filters.views import FilterView

from .filters import ItemFilterSet
from .forms import ItemForm
from .models import Item


# 未ログインのユーザーにアクセスを許可する場合は、LoginRequiredMixinを継承から外してください。
#
# LoginRequiredMixin：未ログインのユーザーをログイン画面に誘導するMixin
# 参考：https://docs.djangoproject.com/ja/2.1/topics/auth/default/#the-loginrequired-mixin

class ItemFilterView(LoginRequiredMixin, FilterView):
    """
    ビュー：一覧表示画面

    以下のパッケージを使用
    ・django-filter 一覧画面(ListView)に検索機能を追加
    https://django-filter.readthedocs.io/en/master/
    """
    model = Item

    # django-filter 設定
    filterset_class = ItemFilterSet
    # django-filter ver2.0対応 クエリ未設定時に全件表示する設定
    strict = False

    # 1ページの表示
    paginate_by = 10

    def get(self, request, **kwargs):
        """
        リクエスト受付
        セッション変数の管理:一覧画面と詳細画面間の移動時に検索条件が維持されるようにする。
        """

        # 一覧画面内の遷移(GETクエリがある)ならクエリを保存する
        if request.GET:
            request.session['query'] = request.GET
        # 詳細画面・登録画面からの遷移(GETクエリはない)ならクエリを復元する
        else:
            request.GET = request.GET.copy()
            if 'query' in request.session.keys():
                for key in request.session['query'].keys():
                    request.GET[key] = request.session['query'][key]

        return super().get(request, **kwargs)

    def get_queryset(self):
        """
        ソート順・デフォルトの絞り込みを指定
        """
        # デフォルトの並び順として、登録時間（降順）をセットする。
        return Item.objects.all().order_by('-created_at')

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        表示データの設定
        """
        # 表示データを追加したい場合は、ここでキーを追加しテンプレート上で表示する
        # 例：kwargs['sample'] = 'sample'
        return super().get_context_data(object_list=object_list, **kwargs)


class ItemDetailView(LoginRequiredMixin, DetailView):
    """
    ビュー：詳細画面
    """
    model = Item

    def get_context_data(self, **kwargs):
        """
        表示データの設定
        """
        # 表示データの追加はここで 例：
        # kwargs['sample'] = 'sample'
        return super().get_context_data(**kwargs)


class ItemCreateView(LoginRequiredMixin, CreateView):
    """
    ビュー：登録画面
    """
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        """
        登録処理
        """
        item = form.save(commit=False)
        item.created_by = self.request.user
        item.created_at = timezone.now()
        item.updated_by = self.request.user
        item.updated_at = timezone.now()
        item.save()

        return HttpResponseRedirect(self.success_url)


class ItemUpdateView(LoginRequiredMixin, UpdateView):
    """
    ビュー：更新画面
    """
    model = Item
    form_class = ItemForm
    success_url = reverse_lazy('index')

    def form_valid(self, form):
        """
        更新処理
        """
        item = form.save(commit=False)
        item.updated_by = self.request.user
        item.updated_at = timezone.now()
        item.save()

        return HttpResponseRedirect(self.success_url)


class ItemDeleteView(LoginRequiredMixin, DeleteView):
    """
    ビュー：削除画面
    """
    model = Item
    success_url = reverse_lazy('index')

    def delete(self, request, *args, **kwargs):
        """
        削除処理
        """
        item = self.get_object()
        item.delete()

        return HttpResponseRedirect(self.success_url)

app/templates/app/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>サンプルアプリ</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/css/bootstrap-datepicker.min.css">
    <link href="{% static "app/css/app.css" %}" rel="stylesheet">
</head>

<body>
<nav class="navbar navbar-expand-md navbar-light bg-light ">
    <a class="navbar-brand" href="#">サンプルアプリ</a>
    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber"
            aria-expanded="false"
            aria-label="ナビゲーションの切替">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="Navber">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">管理画面</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:logout' %}">ログアウト</a>
            </li>
        </ul>
    </div>
</nav>
{% block content %}
{% endblock %}

<!-- jQuery first, then Tether, then Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js"
        integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"
        charset="UTF-8">></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/locales/bootstrap-datepicker.ja.min.js"></script>
<script src="{% static "app/js/plugins/responsive-paginate.js" %}"></script>
<script src="{% static "app/js/app.js" %}"></script>
</body>

</html>

app/templates/app/_pagination.html
{% load item_extras %}
<ul class="pagination">
    {% if page_obj.has_previous %}
        <li class="page-item pagination-prev">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link">&laquo;</span>
        </li>
    {% endif %}
    {% for page in page_obj.paginator.page_range %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active page-item">
                    <span class="page-link">{{ page }}
                        <span class="page-link sr-only">(current)</span>
                    </span>
                </li>
            {% else %}
                <li class="page-item">
                    <a class="page-link" href="?{% url_replace request 'page' page %}">{{ page }}</a>
                </li>
            {% endifequal %}
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li class="page-item pagination-next">
            <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}">&raquo;</a>
        </li>
    {% else %}
        <li class="disabled page-item pagination-next">
            <span class="page-link ">&raquo;</span>
        </li>
    {% endif %}
</ul>

app/templates/app/item_confirm_delete.html
{% extends "./_base.html" %}
<!--  -->
{% block content %}
    <div class="container">
        <h2 class="text-center">データ削除</h2>
        <p>このデータを削除します。よろしいですか？</p>

        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right">
                        <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-outline-dark delete" value="削除"/>
                    </div>
                </div>
            </div>
            {% include "./item_detail_contents.html" %}
            <div class="row">
                <div class="col-12">
                    <div class="float-right mb-3">
                        <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                        <input type="submit" class="btn btn-outline-dark delete" value="削除"/>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

app/templates/app/item_detail.html
{% extends "./_base.html" %}
{% block content %}
    <div class="container">
        <h2 class="text-center">詳細表示</h2>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-outline-dark float-right" href="{% url 'index' %}">戻る</a>
            </div>
        </div>
        <!--  -->
        {% include "./item_detail_contents.html" %}
        <div class="row">
            <div class="col-12">
                <a class="btn btn-outline-dark float-right" href="{% url 'index' %}">戻る</a>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/item_detail_contents.html
<div class="row">
    <div class="col-5 col-sm-3">
        <p>1_文字列</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_1|default_if_none:"未入力"  }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>2_メモ</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_2|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>3_整数</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_3|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>4_浮動小数点</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_4|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>5_固定小数点</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{  item.sample_5|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>6_ブール値</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_6|yesno:"はい,いいえ" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>7_日付</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_7|date:"Y年m月d日" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>8_日時</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_8|date:"Y年m月d日 G時i分s秒" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>9_選択肢（固定）</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.get_sample_9_display|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>10_選択肢（マスタ連動）</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.sample_10.get_full_name|default_if_none:"未入力" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>作成時間</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新者</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_by.get_full_name }}</p>
    </div>
</div>
<div class="row">
    <div class="col-5 col-sm-3">
        <p>更新時間</p>
    </div>
    <div class="col-7 col-sm-9">
        <p>{{ item.updated_at|date:"Y/m/d G:i:s" }}</p>
    </div>
</div>

app/templates/app/item_filter.html
{% extends "./_base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="container">
        <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">検索条件</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form id="filter" method="get">
                        <div class="modal-body">
                            {{ filter.form|crispy }}
                        </div>
                    </form>
                    <div class="modal-footer">
                        <a class="btn btn-outline-dark" data-dismiss="modal">戻る</a>
                        <button type="submit" class="btn btn-outline-dark" form="filter">検索</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a class="btn btn-secondary filtered" style="visibility:hidden" href="/?page=1">検索を解除</a>
                <div class="float-right mt-1">
                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <ul class="list-group">
                    {% for item in item_list %}
                        <li class="list-group-item">
                            {# item_detail_contents.html を参考に必要な項目を追加してください #}
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>1_文字列</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_1|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>2_メモ</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_2|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>3_整数</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.sample_3|default_if_none:"未入力" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成者</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_by.get_full_name }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-5 col-sm-3">
                                    <p>作成時間</p>
                                </div>
                                <div class="col-7 col-sm-9">
                                    <p>{{ item.created_at|date:"Y/m/d G:i:s" }}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12">
                                    <div class="float-right">
                                        <a class="btn btn-outline-dark " href="{% url 'detail' item.pk %}">詳細</a>
                                        <a class="btn btn-outline-dark " href="{% url 'update' item.pk %}">編集</a>
                                        <a class="btn btn-outline-dark " href="{% url 'delete' item.pk %}">削除</a>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% empty %}
                        <li class="list-group-item">
                            対象のデータがありません
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10 mx-auto">
                {% include "./_pagination.html" %}
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right mt-1 mb-3">
                    <a class="btn btn-outline-dark" href="{% url 'create' %}">新規</a>
                    <a class="btn btn-outline-dark" data-toggle="modal" data-target="#myModal" href="#">検索</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/app/item_form.html
{% extends "./_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    {{ form.certifications.errors }}
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="text-center">登録・更新</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right">
                    <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                    <a class="btn btn-outline-dark save" href="#">保存</a>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <form method="post" id="myform">
                    {% crispy form %}
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="float-right mb-3">
                    <a class="btn btn-outline-dark" href="{% url 'index' %}">戻る</a>
                    <a class="btn btn-outline-dark save" href="#">保存</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}